platform :ios, '14.0'

target 'ImageManipulator' do
  use_frameworks!

  # KMP shared module
  pod 'shared', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |build_phase|
      if build_phase.respond_to?(:name) && build_phase.name.include?("Embed") && target.name == "shared"
        target.build_phases.delete(build_phase)
      end
    end
  end

  # Modify application target to remove duplicate framework embedding
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:name) && build_phase.name.include?("Embed Frameworks")
          build_phase.files_references.each do |file_ref|
            if file_ref.path.include?("shared.framework")
              build_phase.remove_file_reference(file_ref)
            end
          end
        end
      end
    end
  end
end
