name: ImageManipulator
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 14.0
  createIntermediateGroups: true
targets:
  ImageManipulator:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    sources:
      - ImageManipulatorSwiftApp
      - ImageManipulator
      - Info.plist
      - LaunchScreen.storyboard
    info:
      path: ./Info.plist
      properties:
        CFBundleIdentifier: "com.example.ImageManipulator"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to let you select images to manipulate."
    settings:
      base:
        DEVELOPMENT_TEAM: "" # Set your development team ID here if you have one
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: ""
        VALID_ARCHS: "arm64 x86_64"
        # Use CocoaPods inherited settings
        FRAMEWORK_SEARCH_PATHS: "$(inherited)"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
    # We're now using CocoaPods to manage the shared framework,
    # so we don't need to explicitly list it as a dependency here